<a href="https://colab.research.google.com/github/ruudtje21/html-portofolio/blob/main/Modul_5_Habis_Kerja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Selamat Datang di Notebook Modul 5 Habis Kerja !
## Kita akan membahas mengenai Modelling dengan Python
Berikut ini adalah daftar isi dari Notebook ini: <br>

1. Data Preparation
2. Finding Data Insight
3. Data Manipulation
4. Modelling Preparation
5. Modelling
6. Modelling Evaluation

detail untuk tutorial markdown ada [disini](https://ingeh.medium.com/markdown-for-jupyter-notebooks-cheatsheet-386c05aeebed)

# 1. Data Preparation

## Import Packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# import sklearn libraries
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.cluster import KMeans

# import whats more?

## Data Overview

In [2]:
data_path = os.path.join("Titanic", "train.csv")
data_path_1 = "Lead Scoring.csv"
data_path_2 = r"Titanic\train.csv"
print(data_path)

Titanic/train.csv

In [5]:
# data = pd.read_csv("nama_data.csv")
data = pd.read_csv('train.csv')

In [6]:
# check jumlah baris (records) dan jumlah column
data.shape # outputnya adalah (baris, kolom)

(891, 12)

### Keterangan data:
1. PassengerId : Id dari records/penumpang
2. Survived : Catatan bahwa dia selamat atau meninggal (1=Selamat, 0=Meninggal)
3. Pclass : Kelas dari penumpang
4. Name : Nama penumpang
5. Sex : Jenis Kelamin penumpang
6. Age : Usia penumpang
7. SibSp : Jumlah Siblings/Spouse (saudara atau pasangan)
8. Parch : Jumlah Parent/Childern (Orang tua atau anak)
9. Ticket : Nomor Tiket
10. Fare : Harga Tiket
11. Cabin : Posisi duduk/kabin penumpang
12. Embarked : Pelabuhan tempat penumpang berangkat

In [7]:
# melihat overview data (top 5 teratas)
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
# melihat overview data (top 5 terbawah)
data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [9]:
# melihat overview data (random 5 data)
data.sample(5, random_state=91)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.0,0,2,F.C.C. 13529,26.2500,NaN,S
561,562,0,3,"Sivic, Mr. Husein",male,40.0,0,0,349251,7.8958,NaN,S
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.0,0,2,113503,211.5000,C82,C
636,637,0,3,"Leinonen, Mr. Antti Gustaf",male,32.0,0,0,STON/O 2. 3101292,7.9250,NaN,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C

In [10]:
# melihat tipe data dari masing-masing kolom dan jumlah baris/records yang kosong
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## Data Quality Check

In [11]:
# check nilai-nilai yang ada di suatu kolom
# data["nama kolom"].unique()
data["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [12]:
# melihat persebaran data (min, max, Quantile)
# data.describe() # untuk data numeric

data.describe(include=['O']) # untuk data categoric

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [13]:
# melihat apakah ada kolom yang nilainya kosong
data.isnull().sum() # melihat jumlah value yang kosong

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [14]:
data.isna().mean() * 100 # persentase baris yang kosong dari keseluruhan

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

## Handling Missing Values

In [15]:
# drop records atau baris
data_dropped = data.dropna()
data_dropped.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [16]:
data.shape, data_dropped.shape

((891, 12), (183, 12))

In [17]:
# drop variable atau kolom
data_dropped = data.drop(columns=['Cabin'], axis=1)
data_dropped.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [ ]:
data.shape, data_dropped.shape

((891, 12), (891, 11))

In [ ]:
# mengisi records atau baris

# data_dropped = data_dropped.fillna(0)
data_dropped['Embarked_filled'] = data_dropped['Embarked'].fillna('Kosong') # atau missing

In [ ]:
data_dropped.loc[data_dropped['Embarked'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Embarked_filled
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,NaN,Kosong
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,NaN,Kosong

In [ ]:
data_dropped['Age'] = data_dropped['Age'].fillna(method='ffill')
data_dropped['Age'] = data_dropped['Age'].fillna(method='bfill')
data_dropped['Age'] = data_dropped['Age'].fillna(data_dropped['Age'].mean())

data_dropped['Embarked'] = data_dropped['Embarked'].fillna(data_dropped['Embarked'].value_counts().idxmax())

In [ ]:
data_dropped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId        891 non-null int64
Survived           891 non-null int64
Pclass             891 non-null int64
Name               891 non-null object
Sex                891 non-null object
Age                891 non-null float64
SibSp              891 non-null int64
Parch              891 non-null int64
Ticket             891 non-null object
Fare               891 non-null float64
Embarked           891 non-null object
Embarked_filled    891 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## Handling Duplicated Values

In [ ]:
data = data.append(data.loc[1], ignore_index=True)

In [ ]:
# check baris yang duplikat
data.loc[data['Name'].duplicated()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
891,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [ ]:
# membuang baris duplikat semuanya
data.drop_duplicates(keep=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# membuang baris duplikat semua, kecuali paling atas
data.drop_duplicates(keep='first')

# membuang baris duplikat semua, kecuali paling bawah
data.drop_duplicates(keep='last')

# membuang baris duplikat berdasarkan beberapa kolom
data.drop_duplicates(subset=['Name', 'Sex'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# 2. Finding Data Insight

In [ ]:
# agregat data berdasarkan suatu kolom
# data.groupby('Kelas').mean()[['Nilai']]
data.groupby('Sex').mean()[['Age']]

              Age
Sex
female  27.954198
male    30.726645

In [ ]:
# menghitung hubungan antara dua variable
# pd.crosstab(data['Kelas'], data['Ikut Bimbel'])
pd.crosstab(data['Sex'], data['Embarked'], normalize=True) # normalize=True
# pd.crosstab(data['Sex'], data['Embarked'])

Embarked         C         Q         S
Sex
female    0.083146  0.040449  0.228090
male      0.106742  0.046067  0.495506

# 3. Data Manipulation

## Binning

In [ ]:
# membagi data sesuai quantilnya
pd.qcut(data['Age'], 5)

0       (19.0, 25.0]
1       (32.0, 41.0]
2       (25.0, 32.0]
3       (32.0, 41.0]
4       (32.0, 41.0]
           ...
887    (0.419, 19.0]
888              NaN
889     (25.0, 32.0]
890     (25.0, 32.0]
891     (32.0, 41.0]
Name: Age, Length: 892, dtype: category
Categories (5, interval[float64]): [(0.419, 19.0] < (19.0, 25.0] < (25.0, 32.0] < (32.0, 41.0] < (41.0, 80.0]]

In [ ]:
pd.qcut(data['Age'], 4).value_counts()

(20.25, 28.0]     183
(0.419, 20.25]    179
(38.0, 80.0]      177
(28.0, 38.0]      176
Name: Age, dtype: int64

In [ ]:
# membagi data secara custom, misal nilai <75 adalah nilai tidak lulus
data_dropped['is_childern'] = np.where(data_dropped['Age']<17, 'Yes', 'No')

data_dropped['age_group'] = np.where(data_dropped['Age']<17, 'Childern', 'Youngster')
data_dropped['age_group'] = np.where(data_dropped['Age']>=40, 'Adult', data_dropped['age_group'])

In [ ]:
# data_dropped.loc[data_dropped['is_childern']=='Yes']
data_dropped.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Embarked_filled,is_childern,age_group
562,563,0,2,"Norman, Mr. Robert Douglas",male,28.0,0,0,218629,13.5000,S,S,No,Youngster
487,488,0,1,"Kent, Mr. Edward Austin",male,58.0,0,0,11771,29.7000,C,C,No,Adult
591,592,1,1,"Stephenson, Mrs. Walter Bertram (Martha Eustis)",female,52.0,1,0,36947,78.2667,C,C,No,Adult
369,370,1,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,C,C,No,Youngster
174,175,0,1,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,C,C,No,Adult
627,628,1,1,"Longley, Miss. Gretchen Fiske",female,21.0,0,0,13502,77.9583,S,S,No,Youngster
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.0,0,1,24160,211.3375,S,S,Yes,Childern
214,215,0,3,"Kiernan, Mr. Philip",male,30.0,1,0,367229,7.7500,Q,Q,No,Youngster
17,18,1,2,"Williams, Mr. Charles Eugene",male,2.0,0,0,244373,13.0000,S,S,Yes,Childern
175,176,0,3,"Klasen, Mr. Klas Albin",male,18.0,1,1,350404,7.8542,S,S,No,Youngster

## Transform

In [ ]:
# menambah kolom jumlah dari dua nilai
data_dropped['family_size'] = (data_dropped['SibSp'] + data_dropped['Parch'])

In [ ]:
# mengubah data kebentuk lain
data_dropped['sqrd_fare'] = data_dropped['Fare'] ** 2
data_dropped['log_fare'] = np.log(data_dropped['Fare'])

C:\ProgramData\Anaconda3\envs\env_crowd\lib\site-packages\pandas\core\series.py:853: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [ ]:
data_dropped.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Embarked_filled,is_childern,age_group,family_size,sqrd_fare,log_fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,S,No,Youngster,1,52.562500,1.981001
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C,No,Youngster,1,5081.308859,4.266662
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,S,No,Youngster,0,62.805625,2.070022
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,S,No,Youngster,1,2819.610000,3.972177
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,S,No,Youngster,0,64.802500,2.085672

## Clipping

In [ ]:
# membatasi nilai dari 1 - 100
data_dropped['Age'] = data_dropped['Age'].clip(1, 100)

In [ ]:
data_dropped['Age'].describe()

count    891.000000
mean      29.584175
std       14.549419
min        1.000000
25%       20.000000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [ ]:
# clipping dengan boxplot
Q1 = data_dropped['Fare'].quantile(0.25)
Q3 = data_dropped['Fare'].quantile(0.75)
IQR = Q3 - Q1
Lwishker = Q1 - 1.5 * IQR
Uwishker = Q3 + 1.5 * IQR
data_dropped['clipped_fare'] = data_dropped['Fare'].clip(Lwishker, Uwishker)

In [ ]:
data_dropped['clipped_fare'].describe()

count    891.000000
mean      24.046813
std       20.481625
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max       65.634400
Name: clipped_fare, dtype: float64

In [ ]:
data_dropped['Fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

## Scaling

In [ ]:
# import sklearn libraries
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# StandardScaller
scaler1 = StandardScaler()
std_scaler = scaler1.fit_transform(data_dropped[['clipped_fare']])

In [ ]:
# MinMaxScaller
scaler2 = MinMaxScaler()
mm_scaler = scaler2.fit_transform(data_dropped[['clipped_fare']])

In [ ]:
data_dropped['std_fare'] = std_scaler
data_dropped['mm_fare'] = mm_scaler

In [ ]:
data_dropped[['clipped_fare', 'std_fare', 'mm_fare']].sample(10, random_state=91)

     clipped_fare  std_fare   mm_fare
535       26.2500  0.107629  0.399943
561        7.8958 -0.789004  0.120300
377       65.6344  2.031623  1.000000
636        7.9250 -0.787578  0.120745
34        65.6344  2.031623  1.000000
79        12.4750 -0.565302  0.190068
430       26.5500  0.122285  0.404513
890        7.7500 -0.796127  0.118078
729        7.9250 -0.787578  0.120745
287        7.8958 -0.789004  0.120300

In [ ]:
data_dropped[['clipped_fare', 'std_fare', 'mm_fare']].describe()

       clipped_fare      std_fare     mm_fare
count    891.000000  8.910000e+02  891.000000
mean      24.046813  9.968332e-17    0.366375
std       20.481625  1.000562e+00    0.312056
min        0.000000 -1.174727e+00    0.000000
25%        7.910400 -7.882908e-01    0.120522
50%       14.454200 -4.686152e-01    0.220223
75%       31.000000  3.396748e-01    0.472313
max       65.634400  2.031623e+00    1.000000

## Encoding

In [ ]:
data_dropped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 20 columns):
PassengerId        891 non-null int64
Survived           891 non-null int64
Pclass             891 non-null int64
Name               891 non-null object
Sex                891 non-null object
Age                891 non-null float64
SibSp              891 non-null int64
Parch              891 non-null int64
Ticket             891 non-null object
Fare               891 non-null float64
Embarked           891 non-null object
Embarked_filled    891 non-null object
is_childern        891 non-null object
age_group          891 non-null object
family_size        891 non-null int64
sqrd_fare          891 non-null float64
log_fare           891 non-null float64
clipped_fare       891 non-null float64
std_fare           891 non-null float64
mm_fare            891 non-null float64
dtypes: float64(7), int64(6), object(7)
memory usage: 139.3+ KB

In [ ]:
col = sorted(data_dropped['Sex'].unique().tolist()) + sorted(data_dropped['Embarked'].unique().tolist()) + sorted(data_dropped['is_childern'].unique().tolist())

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Membuat variabel enc yang berisi class OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')

# mengubah value 'Sex' menjadi encoder 1-0
enc_df = pd.DataFrame(enc.fit_transform(data_dropped[['Sex', 'Embarked', 'is_childern']]).toarray(),
                      columns=col) #

# merge with main df bridge_df on key values
hasil_df = data_dropped[['Sex', 'Embarked', 'is_childern']].join(enc_df) #
hasil_df

        Sex Embarked is_childern  female  male    C    Q    S   No  Yes
0      male        S          No     0.0   1.0  0.0  0.0  1.0  1.0  0.0
1    female        C          No     1.0   0.0  1.0  0.0  0.0  1.0  0.0
2    female        S          No     1.0   0.0  0.0  0.0  1.0  1.0  0.0
3    female        S          No     1.0   0.0  0.0  0.0  1.0  1.0  0.0
4      male        S          No     0.0   1.0  0.0  0.0  1.0  1.0  0.0
..      ...      ...         ...     ...   ...  ...  ...  ...  ...  ...
886    male        S          No     0.0   1.0  0.0  0.0  1.0  1.0  0.0
887  female        S          No     1.0   0.0  0.0  0.0  1.0  1.0  0.0
888  female        S          No     1.0   0.0  0.0  0.0  1.0  1.0  0.0
889    male        C          No     0.0   1.0  1.0  0.0  0.0  1.0  0.0
890    male        Q          No     0.0   1.0  0.0  1.0  0.0  1.0  0.0

[891 rows x 10 columns]

In [ ]:
# pandas dummies
dummies = pd.get_dummies(data_dropped[['Sex', 'Embarked', 'is_childern']], drop_first=True) #
final_data = data_dropped.join(dummies)
dummies.head()

   Sex_male  Embarked_Q  Embarked_S  is_childern_Yes
0         1           0           1                0
1         0           0           0                0
2         0           0           1                0
3         0           0           1                0
4         1           0           1                0

# 4. Modeling Preparation

In [ ]:
final_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked', 'Embarked_filled', 'is_childern',
       'age_group', 'family_size', 'sqrd_fare', 'log_fare', 'clipped_fare',
       'std_fare', 'mm_fare', 'Sex_male', 'Embarked_Q', 'Embarked_S',
       'is_childern_Yes'],
      dtype='object')

In [ ]:
final_data = final_data.drop(['PassengerId', 'Name', 'Sex', 'Embarked', 'Embarked_filled', 'Ticket', 'is_childern'], 1)

In [ ]:
# import libraries
from sklearn.model_selection import train_test_split

train, test = train_test_split(final_data, test_size=0.3, random_state=2021)

In [ ]:
train.shape, test.shape

((623, 17), (268, 17))

# 5. Modeling

In [ ]:
train.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'age_group',
       'family_size', 'sqrd_fare', 'log_fare', 'clipped_fare', 'std_fare',
       'mm_fare', 'Sex_male', 'Embarked_Q', 'Embarked_S', 'is_childern_Yes'],
      dtype='object')

In [ ]:
from sklearn.linear_model import LinearRegression
# predictor = X, Target = y

X_train = train.drop(['Fare', 'mm_fare', 'sqrd_fare', 'log_fare', 'clipped_fare', 'std_fare', 'age_group'], 1)
y_train = train['Fare']
X_test = test.drop(['Fare', 'mm_fare', 'sqrd_fare', 'log_fare', 'clipped_fare', 'std_fare', 'age_group'], 1)
y_test = test['Fare']

lr = LinearRegression(normalize=True)
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [ ]:
X_test[2:3]

,Survived,Pclass,Age,SibSp,Parch,family_size,Sex_male,Embarked_Q,Embarked_S,is_childern_Yes
666,0,2,25.0,0,0,0,1,0,1,0

In [ ]:
lr.predict(X_test[2:3])

array([30.91559742])

In [ ]:
?LinearRegression

In [ ]:
from sklearn.tree import DecisionTreeClassifier

X_train = train.drop(['Survived', 'Fare', 'mm_fare', 'sqrd_fare', 'log_fare', 'std_fare', 'age_group'], 1)
y_train = train['Survived']
X_test = test.drop(['Survived', 'Fare', 'mm_fare', 'sqrd_fare', 'log_fare',  'std_fare', 'age_group'], 1)
y_test = test['Survived']

dt = DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=2021)
dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=2021, splitter='best')

In [ ]:
?DecisionTreeClassifier

In [ ]:
from sklearn.cluster import KMeans

X_train = train.drop(['Survived', 'log_fare', 'std_fare', 'age_group'], 1)
X_test = test.drop(['Survived', 'log_fare',  'std_fare', 'age_group'], 1)

kmeans = KMeans(n_clusters=5, max_iter=100)
kmeans.fit(X_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=100,
       n_clusters=5, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [ ]:
?KMeans

# 6. Modelling Evaluation

In [ ]:
# import libraries
from sklearn.metrics import mean_squared_error, accuracy_score, precision_score, recall_score, silhouette_score

In [ ]:
# Regression
y_pred = lr.predict(X_test)
mean_squared_error(y_test, y_pred)

1442.4150849173345

In [ ]:
# Classification
y_pred = dt.predict(X_test)
acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
print(acc, prec, recall)

0.7910447761194029 0.7831325301204819 0.6310679611650486

In [ ]:
# Clustering
silhouette_score(X_train, kmeans.labels_)

0.8943843094223066